pipeline:
  name: "example_pipeline_1"
  jobs:
    - jobname: "example_job_1"

      trigger:
          type: "cron"
          value: "0 1 * * *"
      
      source:
          type: "clickhouse"
          db: "db1"
          query: "SELECT * FROM crime_data FORMAT CSV"
          
      transformations:
          definition: "sample_transformation_config.yaml"
          
      quality_checks:
        - type: "completeness"
          rules: "completeness_rules.yaml"
          
      destination:
          type: "s3"
          bucket: "test"
          filename: "xyz.csv"

    - jobname: "example_job_2"

      trigger:
        - type: "cron"
          value: "10 1 * * *"

      source:
          type: "s3"
          bucket: "test"
          filename: "xyz.csv"

      transformations:
        - definition: "sample_transformation_config2.yaml"

      quality_checks:
        - type: "completeness"
          rules: "completeness_rules.yaml"

      destination:
        - type: "s3"
          bucket: "bucket_name"