name: "Transformation2"
import:
  "./docs/SampleScalaTransform2.scala"

inputs:
  - [lsoa_code, String]
  - [borough, String]
  - [major_category, String]
  - [minor_category, String]
  - [value, Int]
  - [dateYYYYMMStr, String]

## input type MUST have functions that do not change datatype
## if datatype changes must be made, use a derived type and drop the original column
outputs:
  -   col: "borough"
      type: "input"
      function: "toUpper"