pipeline:
  name: "example_pipeline_1"
  jobs:
    - jobname: "example_job_1"

      trigger:
        - type: "cron"
          value: "0 1 * * *"
      
      source:
          type: "postgres"
          db: "db1"
          query: "SELECT * FROM table"
          
      transformations:
          definition: "transformation.yaml"
          
      quality_checks:
        - type: "completeness"
          rules: "completeness_rules.yaml"
          
      destination:
          type: "s3"
          bucket: "bucket_name"

    - jobname: "example_job_2"

      trigger:
        - type: "dependent"
          value: "job1"
      
      source:
        - type: "s3"
          bucket: "bucket2"
          
      transformations:
        - definition: "transformation2.yaml"
          
      quality_checks:
        - type: "completeness"
          rules: "completeness_rules.yaml"

      destination:
        - type: "s3"
          bucket: "bucket_name"